openapi: '3.1.0'

info:
  title: User Management API
  version: 2.0.0

servers:
  - url: http://localhost:3000/api
    description: Optional server description, e.g. Main (production) server

paths:
  /users:
    $ref: './user.yaml#/paths/~1users'
  /users/{userId}:
    $ref: './user.yaml#/paths/~1users~1{userId}'
