import Main from '@/components/layout/main'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Providers from '@/components/layout/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  params: { lang: string }
  children: React.ReactNode
}) {
  const { lang } = params
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Providers>
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  )
}
